# Analisis estadistico Categoria U13
En la presente Notebook se generara el estudio de las estadisticas para todos los equipos que pasaron el 2025 por la categoria A1

## Librerias y funciones utilizadas
Ignorar esta seccion

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import sys
sys.path.append('./Funciones')

In [5]:
from top10goleadores import top_20_jugadores_puntos
from top_20_asistidores import top_20_asistidores
from top_20_t2c import top_20_t2c
from top_20_t3c import top_20_t3c
from top_20_t1c import top_20_t1c
from top_20_recuperos import top_20_recuperos
from top_20_rd import top_20_rd
from top_20_ro import top_20_ro
from top_20_rt import top_20_rt
from top_20_faltas import top_20_faltas

---

# Estadisticas convencionales

## Maximos Goleadores

In [6]:
top_20_jugadores_puntos('EstadisticasGlobales.csv')

                                       Jugador  Puntos              Club
183                 LOZA DIAZ, ARTURO BAUTISTA   469.0             Pesca
91                        DI RIENZO, JUAN CRUZ   425.0       Santo Tomas
169        LEDESMA SPILERE , JOAQUIN LEONARDO    415.0           Empalme
229                NAZARALA SASTRE, JUAN PABLO   410.0       Santo Tomas
307                              SONA, FACUNDO   397.0  Banco de Cordoba
230                            OBERTI, FACUNDO   370.0             Banco
88                    DA VIA, GENARO FRANCESCO   341.0             Pesca
107                         FELSZTYNA, AGUSTIN   314.0       Macabi-Noar
139               GONZALEZ SCHIEBEL, FRANCISCO   310.0     Poeta Lugones
336                        VALDES, TOMAS SIMON   300.0     Universitario
204                        MASQUIJO, FRANCISCO   293.0   Dante Alighieri
160                     KAPLINSKY , MANU DAVID   280.0       Macabi-Noar
201                    MARTINEZ ROSSI, LAUTARO   276.0             Pesca
102                          ESPINOSA, IGNACIO   271.0     Universitario
187                            LUKACH, BENICIO   265.0             Pesca
147                GUZMAN, LAUTARO MAXIMILIANO   253.0             Pesca
168             LEANZA AGUILERA, MATIAS LEONEL   250.0           Empalme
203                 MARTINEZ ZAMORA, VALENTINO   242.0  Banco de Cordoba
205                  MATTOS MANASSERO, TIZIANO   240.0             Pesca
175  LICARI RODRIGUEZ CUSCUETA, AGUSTIN JAVIER   223.0       Santo Tomas

## Maixmos Asistidores

In [7]:
top_20_asistidores('EstadisticasGlobales.csv')

                               Jugador   AST              Club
336                VALDES, TOMAS SIMON  57.0     Universitario
203         MARTINEZ ZAMORA, VALENTINO  53.0  Banco de Cordoba
307                      SONA, FACUNDO  51.0  Banco de Cordoba
230                    OBERTI, FACUNDO  48.0             Banco
187                    LUKACH, BENICIO  46.0             Pesca
88            DA VIA, GENARO FRANCESCO  45.0             Pesca
91                DI RIENZO, JUAN CRUZ  44.0       Santo Tomas
139       GONZALEZ SCHIEBEL, FRANCISCO  41.0     Poeta Lugones
41                   BRANDAN, SANTIAGO  36.0     Universitario
0              ACEVEDO, PABLO EZEQUIEL  35.0     Universitario
277                     RIVETTA, LUCAS  34.0             Pesca
205          MATTOS MANASSERO, TIZIANO  34.0             Pesca
183         LOZA DIAZ, ARTURO BAUTISTA  32.0             Pesca
39                      BOTTA, FACUNDO  32.0       Santo Tomas
201            MARTINEZ ROSSI, LAUTARO  32.0             Pesca
84                   COVASSI, FEDERICO  30.0  Banco de Cordoba
135           GOMEZ MACHNOWSKY, FELIPE  29.0       Santo Tomas
296            SANCHEZ, THIAGO NICOLAS  26.0           Empalme
109      FERNANDEZ ECHEVESTE, LEONIDAS  26.0  Banco de Cordoba
2    AHUMADA TORRES, NICOLAS ANTONIO    26.0   Union Electrica

## Maximos en Faltas

In [8]:
top_20_faltas('EstadisticasGlobales.csv')

                                 Jugador  Faltas             Club
336                  VALDES, TOMAS SIMON    90.0    Universitario
6     ALLENDE BORDOLINI, FRANCESCA SOFÍA    73.0    Universitario
169  LEDESMA SPILERE , JOAQUIN LEONARDO     71.0          Empalme
278                      RIZZO, VALENTIN    69.0    Universitario
107                   FELSZTYNA, AGUSTIN    66.0      Macabi-Noar
229          NAZARALA SASTRE, JUAN PABLO    64.0      Santo Tomas
230                      OBERTI, FACUNDO    63.0            Banco
232                  OLIVERA ROQUE, CIRO    61.0      Santo Tomas
91                  DI RIENZO, JUAN CRUZ    58.0      Santo Tomas
270     RAPETTI PERALTA, TIAGO BENJAMIN     55.0          Empalme
187                      LUKACH, BENICIO    53.0            Pesca
113                  FERRARETTO, LORENZO    53.0          Empalme
114     FERREYRA CURA, SANTINO SEBASTIAN    52.0    Poeta Lugones
106                  FARÍAS, BRUNO MATEO    51.0    Universitario
318                      SUAREZ, FACUNDO    50.0    Poeta Lugones
135             GOMEZ MACHNOWSKY, FELIPE    50.0      Santo Tomas
88              DA VIA, GENARO FRANCESCO    50.0            Pesca
139         GONZALEZ SCHIEBEL, FRANCISCO    49.0    Poeta Lugones
49                 BURGOS MEALLA , BRUNO    48.0  Dante Alighieri
147          GUZMAN, LAUTARO MAXIMILIANO    45.0            Pesca

## Maximo Anotadores

### Maximo anotador de 2 puntos

In [9]:
top_20_t2c('EstadisticasGlobales.csv')

                                       Jugador    T2C              Club
183                 LOZA DIAZ, ARTURO BAUTISTA  184.0             Pesca
169        LEDESMA SPILERE , JOAQUIN LEONARDO   164.0           Empalme
230                            OBERTI, FACUNDO  158.0             Banco
307                              SONA, FACUNDO  157.0  Banco de Cordoba
91                        DI RIENZO, JUAN CRUZ  155.0       Santo Tomas
88                    DA VIA, GENARO FRANCESCO  149.0             Pesca
107                         FELSZTYNA, AGUSTIN  134.0       Macabi-Noar
201                    MARTINEZ ROSSI, LAUTARO  133.0             Pesca
229                NAZARALA SASTRE, JUAN PABLO  132.0       Santo Tomas
147                GUZMAN, LAUTARO MAXIMILIANO  119.0             Pesca
139               GONZALEZ SCHIEBEL, FRANCISCO  119.0     Poeta Lugones
175  LICARI RODRIGUEZ CUSCUETA, AGUSTIN JAVIER  107.0       Santo Tomas
205                  MATTOS MANASSERO, TIZIANO  107.0             Pesca
336                        VALDES, TOMAS SIMON  105.0     Universitario
187                            LUKACH, BENICIO   99.0             Pesca
168             LEANZA AGUILERA, MATIAS LEONEL   97.0           Empalme
203                 MARTINEZ ZAMORA, VALENTINO   94.0  Banco de Cordoba
204                        MASQUIJO, FRANCISCO   94.0   Dante Alighieri
234                   ONORES RODRIGUEZ, JULIAN   91.0             Pilar
160                     KAPLINSKY , MANU DAVID   91.0       Macabi-Noar

### Maximos anotadores de 3 puntos

In [10]:
top_20_t3c('EstadisticasGlobales.csv')

                                 Jugador   T3C              Club
229          NAZARALA SASTRE, JUAN PABLO  30.0       Santo Tomas
102                    ESPINOSA, IGNACIO  25.0     Universitario
91                  DI RIENZO, JUAN CRUZ  24.0       Santo Tomas
160               KAPLINSKY , MANU DAVID  21.0       Macabi-Noar
204                  MASQUIJO, FRANCISCO  18.0   Dante Alighieri
338     VALENTINO FAZZIO, LEANDRO DANIEL  17.0           Empalme
320                    TAY TOSCO, FELIPE  16.0       Santo Tomas
183           LOZA DIAZ, ARTURO BAUTISTA  14.0             Pesca
187                      LUKACH, BENICIO  14.0             Pesca
203           MARTINEZ ZAMORA, VALENTINO  13.0  Banco de Cordoba
336                  VALDES, TOMAS SIMON  13.0     Universitario
41                     BRANDAN, SANTIAGO  13.0     Universitario
169  LEDESMA SPILERE , JOAQUIN LEONARDO   12.0           Empalme
307                        SONA, FACUNDO  12.0  Banco de Cordoba
57               CAPA, MARCELO EMILIANO   11.0           Alianza
25       BERNHARDT LOBO, DANTE ALEJANDRO  10.0  Banco de Cordoba
139         GONZALEZ SCHIEBEL, FRANCISCO   9.0     Poeta Lugones
6     ALLENDE BORDOLINI, FRANCESCA SOFÍA   9.0     Universitario
277                       RIVETTA, LUCAS   9.0             Pesca
0                ACEVEDO, PABLO EZEQUIEL   8.0     Universitario

### Maximos Anotadores de Tiros Libres

In [11]:
top_20_t1c('EstadisticasGlobales.csv')

                                 Jugador   T1C              Club
183           LOZA DIAZ, ARTURO BAUTISTA  59.0             Pesca
229          NAZARALA SASTRE, JUAN PABLO  56.0       Santo Tomas
169  LEDESMA SPILERE , JOAQUIN LEONARDO   51.0           Empalme
204                  MASQUIJO, FRANCISCO  51.0   Dante Alighieri
307                        SONA, FACUNDO  47.0  Banco de Cordoba
168       LEANZA AGUILERA, MATIAS LEONEL  47.0           Empalme
139         GONZALEZ SCHIEBEL, FRANCISCO  45.0     Poeta Lugones
107                   FELSZTYNA, AGUSTIN  43.0       Macabi-Noar
91                  DI RIENZO, JUAN CRUZ  43.0       Santo Tomas
134                    GIOVETTI, OCTAVIO  38.0             Pilar
160               KAPLINSKY , MANU DAVID  35.0       Macabi-Noar
230                      OBERTI, FACUNDO  33.0             Banco
277                       RIVETTA, LUCAS  31.0             Pesca
332                     TOZZINI, LORENZO  30.0           Empalme
336                  VALDES, TOMAS SIMON  29.0     Universitario
338     VALENTINO FAZZIO, LEANDRO DANIEL  27.0           Empalme
6     ALLENDE BORDOLINI, FRANCESCA SOFÍA  27.0     Universitario
95                         DRUETTA, LEON  26.0             Pilar
187                      LUKACH, BENICIO  25.0             Pesca
88              DA VIA, GENARO FRANCESCO  25.0             Pesca

## Maximo Reboteadores

In [12]:
top_20_rd('EstadisticasGlobales.csv')

                                       Jugador     RD              Club
336                        VALDES, TOMAS SIMON  152.0     Universitario
102                          ESPINOSA, IGNACIO  152.0     Universitario
169        LEDESMA SPILERE , JOAQUIN LEONARDO   141.0           Empalme
88                    DA VIA, GENARO FRANCESCO  136.0             Pesca
234                   ONORES RODRIGUEZ, JULIAN  130.0             Pilar
107                         FELSZTYNA, AGUSTIN  120.0       Macabi-Noar
1      AGUIRRE FARIAS DE LA TORRE, MAXIMO LUIS  120.0       Santo Tomas
307                              SONA, FACUNDO  117.0  Banco de Cordoba
277                             RIVETTA, LUCAS  114.0             Pesca
135                   GOMEZ MACHNOWSKY, FELIPE  113.0       Santo Tomas
106                        FARÍAS, BRUNO MATEO  107.0     Universitario
230                            OBERTI, FACUNDO  102.0             Banco
114           FERREYRA CURA, SANTINO SEBASTIAN  101.0     Poeta Lugones
226                            MUÑOZ, PATRICIO   96.0   Union Electrica
175  LICARI RODRIGUEZ CUSCUETA, AGUSTIN JAVIER   95.0       Santo Tomas
183                 LOZA DIAZ, ARTURO BAUTISTA   93.0             Pesca
91                        DI RIENZO, JUAN CRUZ   92.0       Santo Tomas
139               GONZALEZ SCHIEBEL, FRANCISCO   91.0     Poeta Lugones
213                MONSANTO SUGUER, TIAGO JOSE   88.0       Macabi-Noar
246                  PAREDES BRIZUELA, SANTINO   88.0             Pesca

In [13]:
top_20_ro('EstadisticasGlobales.csv')

                                       Jugador     RO              Club
88                    DA VIA, GENARO FRANCESCO  107.0             Pesca
83                    CORONEL TAMAYO, JERONIMO  101.0             Pesca
175  LICARI RODRIGUEZ CUSCUETA, AGUSTIN JAVIER   84.0       Santo Tomas
135                   GOMEZ MACHNOWSKY, FELIPE   83.0       Santo Tomas
277                             RIVETTA, LUCAS   82.0             Pesca
187                            LUKACH, BENICIO   82.0             Pesca
230                            OBERTI, FACUNDO   82.0             Banco
147                GUZMAN, LAUTARO MAXIMILIANO   80.0             Pesca
109              FERNANDEZ ECHEVESTE, LEONIDAS   69.0  Banco de Cordoba
336                        VALDES, TOMAS SIMON   67.0     Universitario
106                        FARÍAS, BRUNO MATEO   64.0     Universitario
84                           COVASSI, FEDERICO   61.0  Banco de Cordoba
169        LEDESMA SPILERE , JOAQUIN LEONARDO    59.0           Empalme
246                  PAREDES BRIZUELA, SANTINO   59.0             Pesca
1      AGUIRRE FARIAS DE LA TORRE, MAXIMO LUIS   57.0       Santo Tomas
213                MONSANTO SUGUER, TIAGO JOSE   57.0       Macabi-Noar
183                 LOZA DIAZ, ARTURO BAUTISTA   56.0             Pesca
307                              SONA, FACUNDO   56.0  Banco de Cordoba
201                    MARTINEZ ROSSI, LAUTARO   54.0             Pesca
278                            RIZZO, VALENTIN   53.0     Universitario

In [14]:
top_20_rt('EstadisticasGlobales.csv')

                                       Jugador     RT              Club
88                    DA VIA, GENARO FRANCESCO  243.0             Pesca
336                        VALDES, TOMAS SIMON  219.0     Universitario
169        LEDESMA SPILERE , JOAQUIN LEONARDO   200.0           Empalme
135                   GOMEZ MACHNOWSKY, FELIPE  196.0       Santo Tomas
277                             RIVETTA, LUCAS  196.0             Pesca
102                          ESPINOSA, IGNACIO  191.0     Universitario
230                            OBERTI, FACUNDO  184.0             Banco
175  LICARI RODRIGUEZ CUSCUETA, AGUSTIN JAVIER  179.0       Santo Tomas
1      AGUIRRE FARIAS DE LA TORRE, MAXIMO LUIS  177.0       Santo Tomas
307                              SONA, FACUNDO  173.0  Banco de Cordoba
106                        FARÍAS, BRUNO MATEO  171.0     Universitario
234                   ONORES RODRIGUEZ, JULIAN  166.0             Pilar
83                    CORONEL TAMAYO, JERONIMO  160.0             Pesca
107                         FELSZTYNA, AGUSTIN  160.0       Macabi-Noar
147                GUZMAN, LAUTARO MAXIMILIANO  154.0             Pesca
183                 LOZA DIAZ, ARTURO BAUTISTA  149.0             Pesca
246                  PAREDES BRIZUELA, SANTINO  147.0             Pesca
213                MONSANTO SUGUER, TIAGO JOSE  145.0       Macabi-Noar
226                            MUÑOZ, PATRICIO  143.0   Union Electrica
187                            LUKACH, BENICIO  143.0             Pesca

## Maximos Recuperos

In [15]:
top_20_recuperos('EstadisticasGlobales.csv')

                                     Jugador  Recuperos             Club
336                      VALDES, TOMAS SIMON      112.0    Universitario
318                          SUAREZ, FACUNDO       99.0    Poeta Lugones
204                      MASQUIJO, FRANCISCO       94.0  Dante Alighieri
229              NAZARALA SASTRE, JUAN PABLO       90.0      Santo Tomas
187                          LUKACH, BENICIO       89.0            Pesca
139             GONZALEZ SCHIEBEL, FRANCISCO       87.0    Poeta Lugones
41                         BRANDAN, SANTIAGO       83.0    Universitario
1    AGUIRRE FARIAS DE LA TORRE, MAXIMO LUIS       83.0      Santo Tomas
107                       FELSZTYNA, AGUSTIN       80.0      Macabi-Noar
114         FERREYRA CURA, SANTINO SEBASTIAN       79.0    Poeta Lugones
49                     BURGOS MEALLA , BRUNO       76.0  Dante Alighieri
88                  DA VIA, GENARO FRANCESCO       74.0            Pesca
169      LEDESMA SPILERE , JOAQUIN LEONARDO        74.0          Empalme
230                          OBERTI, FACUNDO       73.0            Banco
278                          RIZZO, VALENTIN       72.0    Universitario
47                   BRÜGGER, FEDERICO MATEO       69.0  Dante Alighieri
102                        ESPINOSA, IGNACIO       69.0    Universitario
17                BARTOLI MARTINAT, LEONARDO       68.0  Dante Alighieri
82                       CORIA, CIRO JOAQUIN       67.0  Dante Alighieri
0                    ACEVEDO, PABLO EZEQUIEL       65.0    Universitario